base {
	archivesName = "myriad-essentials"
}

dependencies {
	// Essentials is built exactly like a third-party addon: it only sees Myriad's API.
	implementation project(":core")
}

loom {
	mods {
		"myriad" {
			sourceSet("main", ":core")
		}
		"myriad-essentials" {
			sourceSet sourceSets.main
		}
	}
}
