{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.myriad",
    "module": "myriad-essentials",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myriad-essentials-0.2.8.jar",
          "url": "myriad-essentials-0.2.8.jar",
          "size": 292146,
          "sha512": "1df310a4b858626a6cd5c12bf8276f00c4185a91890d50910cb90d541f37b86c318d62a091a854d3bbe7b18b54b368527acc82ee8c6301a356be32c28bfdae52",
          "sha256": "f6ab51bd7233737f252d69d662e2e404486baeb12ede7cc15b3e796d123c99fe",
          "sha1": "fdacb5731198d4c31c6b7f8513b74ded54bafea2",
          "md5": "23fd003d3a44cfbaf88c52a8f0eb82f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "dev.myriad",
          "module": "myriad",
          "version": {
            "requires": "0.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "myriad-essentials-0.2.8.jar",
          "url": "myriad-essentials-0.2.8.jar",
          "size": 292146,
          "sha512": "1df310a4b858626a6cd5c12bf8276f00c4185a91890d50910cb90d541f37b86c318d62a091a854d3bbe7b18b54b368527acc82ee8c6301a356be32c28bfdae52",
          "sha256": "f6ab51bd7233737f252d69d662e2e404486baeb12ede7cc15b3e796d123c99fe",
          "sha1": "fdacb5731198d4c31c6b7f8513b74ded54bafea2",
          "md5": "23fd003d3a44cfbaf88c52a8f0eb82f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myriad-essentials-0.2.8-sources.jar",
          "url": "myriad-essentials-0.2.8-sources.jar",
          "size": 137499,
          "sha512": "22df44d80c77438b691c203435fc04103c8f61a82b40b4ff4fd49fdd68cf223f31a9dcdaa22e92073be74cee21984980f6eb858557402ae6b8458220663dba5c",
          "sha256": "77bc73fc1c9f661d53f13f2af5eb4127dd3a8a8661eaba38b3f43f8987b0aacb",
          "sha1": "05fab8c5498ebc7b72d12c4d240f589797f68576",
          "md5": "b066c7a8d77c03812b36ed5e9d018fb1"
        }
      ]
    }
  ]
}
