{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.myriad",
    "module": "myriad-essentials",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myriad-essentials-0.2.4.jar",
          "url": "myriad-essentials-0.2.4.jar",
          "size": 282837,
          "sha512": "e042acd3f7272e4725378d6266dea56ef4eff5d4637eb8d8f901d983b31f77edc9fb7658ded1f6616ea2b2ab9c15baa5ff7d67930c03918188e6dd578e5fdcc3",
          "sha256": "9100fda57cf26ae892dd49f9be82635b0876628465a2410f865a8fe36768ab00",
          "sha1": "c12e5d89d16f33c8d575a8f5f1891f71820a6c38",
          "md5": "bfc35dcb4316c784ab5a6bde8ca66754"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.2"
          }
        },
        {
          "group": "dev.myriad",
          "module": "myriad",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "myriad-essentials-0.2.4.jar",
          "url": "myriad-essentials-0.2.4.jar",
          "size": 282837,
          "sha512": "e042acd3f7272e4725378d6266dea56ef4eff5d4637eb8d8f901d983b31f77edc9fb7658ded1f6616ea2b2ab9c15baa5ff7d67930c03918188e6dd578e5fdcc3",
          "sha256": "9100fda57cf26ae892dd49f9be82635b0876628465a2410f865a8fe36768ab00",
          "sha1": "c12e5d89d16f33c8d575a8f5f1891f71820a6c38",
          "md5": "bfc35dcb4316c784ab5a6bde8ca66754"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myriad-essentials-0.2.4-sources.jar",
          "url": "myriad-essentials-0.2.4-sources.jar",
          "size": 129781,
          "sha512": "e0ba89e41d17e05cbdbcb5a4b3ce1780b09e50d27d885de2dac11652564c3ee87244589dbcbb31a867381f73fc12096dd18ff9bfce84d71e9fdc21630f3998d8",
          "sha256": "80eb5879941d044f7dd544ece801a75ffc6f161afbeffd80baab2ed34de65b16",
          "sha1": "22514490cdcb894319704522ae8b55909c7d3196",
          "md5": "a2cc64557d51713c315fbb1915c07dc3"
        }
      ]
    }
  ]
}
